simple: folder rename

diff --git a/sbin/k8s-status b/sbin/k8s-status
--- a/sbin/k8s-status
+++ b/sbin/k8s-status
@@ -7,6 +7,32 @@
 echo -e $BOLD$YELLOW"Kubernetes Status"$NOCOLOR$NOBOLD
 echo
 
+# This for loop waits until kubectl can access the api server that minikube has created.
+for i in {1..150} # timeout for 5 minutes.
+do
+   kubectl get pods &> /dev/null
+   if [ $? -ne 1 ]; then
+      break
+  fi
+  echo 'Error while getting the pods - Sleeping for 2 seconds...'
+  sleep 2
+done
+echo -e $GREEN"kubectl get nodes"$NOCOLOR
+echo
+kubectl get nodes
+echo
+echo -e $GREEN"kubectl get pods --all-namespaces"$NOCOLOR
+echo
+kubectl get pods --all-namespaces
+echo
+echo -e $GREEN"kubectl get services --all-namespaces"$NOCOLOR
+echo
+kubectl get services --all-namespaces
+echo
+echo -e $GREEN"kubectl config view"$NOCOLOR
+echo
+kubectl config view
+echo
 # kubectl commands are now able to interact with minikube cluster.
 echo -e $WHITE_BCK"NODES"$NOCOLOR
 echo
